Enable logging (#298)
# Description

- Added log4j2 logging for Hive

If logging is set to DEBUG, there will be some exceptions due to null values in the XML string from `DataNucleus`.

```
ERROR StatusLogger com.fasterxml.jackson.core.JsonGenerationException: Invalid null character in text to output
 com.fasterxml.jackson.core.JsonGenerationException: Invalid null character in text to output
     at com.fasterxml.jackson.dataformat.xml.util.StaxUtil.throwAsGenerationException(StaxUtil.java:51)
```

Printed null values causing the problem (without XML format):
```
bash-4.4$ sed -n '/\x0/ { s/\x0/<NUL>/g; p}' /stackable/log/test.log
[DEBUG] 2023-01-20 13:33:24.637 [main] Transaction - Transaction created [DataNucleus Transaction, ID=Xid=<NUL><NUL><NUL>, enlisted resources=[]]
[DEBUG] 2023-01-20 13:33:24.647 [main] Transaction - Running enlist operation on resource: org.datanucleus.store.rdbms.ConnectionFactoryImpl$EmulatedXAResource@687e4c93, error code TMNOFLAGS and transaction: [DataNucleus Transaction, ID=Xid=<NUL><NUL><NUL>, enlisted resources=[]]
[DEBUG] 2023-01-20 13:33:24.647 [main] Connection - ManagedConnection(enlisted) "org.datanucleus.store.rdbms.ConnectionFactoryImpl$ManagedConnectionImpl@3b1ed14b [conn=com.zaxxer.hikari.pool.HikariProxyConnection@3727f0ee, commitOnRelease=false, closeOnRelease=false, closeOnTxnEnd=true]" starting for transaction "Xid=<NUL><NUL><NUL>" with flags "0"
[DEBUG] 2023-01-20 13:33:24.698 [main] Transaction - Committing [DataNucleus Transaction, ID=Xid=<NUL><NUL><NUL>, enlisted resources=[org.datanucleus.store.rdbms.ConnectionFactoryImpl$EmulatedXAResource@687e4c93]]
[DEBUG] 2023-01-20 13:33:24.698 [main] Connection - ManagedConnection(enlisted) 
```
## TODO

- [x] Adapt image version in examples, docs, tests 
- [x] Adapt changelog

fixes: https://github.com/stackabletech/hive-operator/issues/290



Co-authored-by: Malte Sander <malte.sander.it@gmail.com>
Co-authored-by: Siegfried Weber <mail@siegfriedweber.net>